### ISSUE TITLE
Better bar visualization

### ISSUE THREAD

**Issue by atnbueno** [tcard/es-covid-notify#1]
I would use

Code | Result | Description
-- | -- | --
U+2592 | ▒ | Medium shade
U+2593 | ▓ | Dark shade
U+2588 | █ | Full block

instead of 

Code | Result | Description
-- | -- | --
U+2591 | ░ | Light shade
U+2592 | ▒ | Medium shade
U+2593 | ▓ | Dark shade

to improve the visualization of the bars, specially in iOS (Tested in Telegram Desktop and Telegram iOS).
![imagen](https://user-images.githubusercontent.com/3778999/119382206-03e5c800-bcc2-11eb-83c9-1d4dc836a868.png)
![IMG_0794](https://user-images.githubusercontent.com/3778999/119382433-4c9d8100-bcc2-11eb-8b15-ced7c7806d44.png)

**Comment by tcard** [comment]
Telegram shouldn't be an issue, since progress bars are inside \<pre\> blocks that make the font monospaced:

<img width="408" alt="Screenshot 2021-05-25 at 10 11 58" src="https://user-images.githubusercontent.com/727422/119463048-a729f200-bd41-11eb-82bb-d0a416bbb068.png">

In Twitter, it's true that this looks pretty bad in iOS/Safari for Mac, but if I follow your suggestion, the age groups bars then look unaligned in Firefox and Chrome (Mac), because full blocks are wider than shade blocks in this font:

<img width="461" alt="Screenshot 2021-05-25 at 10 18 27" src="https://user-images.githubusercontent.com/727422/119463953-8f9f3900-bd42-11eb-9f07-9a3797d2ae13.png">

And still looks bad in iOS/Safari's font:

<img width="388" alt="Screenshot 2021-05-25 at 10 29 59" src="https://user-images.githubusercontent.com/727422/119465663-2b7d7480-bd44-11eb-8ff5-1f1122082956.png">

So, unfortunately the current situation seems to be the best we can do.

**Comment by atnbueno** [comment]
I was wrong about iOS (I didn't check the monospace font).

You're right.  It's the best comprimise.
